[2023-12-20 19:19:11,309: INFO: main: welcome to custom log]
[2023-12-20 19:55:31,638: INFO: main: welcome to custom log]
[2023-12-20 22:22:42,768: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-20 22:22:42,780: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-20 22:22:42,780: INFO: common: created directory at : artifacts]
[2023-12-20 22:22:42,780: INFO: common: created directory at : artifacts/data_ingestion]
[2023-12-20 22:22:42,780: INFO: 3596648662: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-20 22:23:02,895: INFO: 3596648662: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-21 11:34:34,033: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2023-12-21 11:34:34,033: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 11:34:34,035: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 11:34:34,035: INFO: common: created directory at : artifacts]
[2023-12-21 11:34:34,035: INFO: common: created directory at : artifacts/data_ingestion]
[2023-12-21 11:34:34,035: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-21 11:34:49,813: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-21 11:34:50,734: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2023-12-21 13:25:56,722: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:25:56,730: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:25:56,747: INFO: common: created directory at : artifacts]
[2023-12-21 13:25:56,756: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 13:31:09,984: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:31:09,989: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:31:09,989: INFO: common: created directory at : artifacts]
[2023-12-21 13:31:09,989: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 13:32:32,195: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:32:32,201: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:32:32,201: INFO: common: created directory at : artifacts]
[2023-12-21 13:32:32,207: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 13:32:38,623: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:32:38,628: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:32:38,632: INFO: common: created directory at : artifacts]
[2023-12-21 13:32:38,634: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 13:36:28,477: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:36:28,482: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:36:28,484: INFO: common: created directory at : artifacts]
[2023-12-21 13:36:28,485: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 13:37:43,368: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:37:43,372: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:37:43,376: INFO: common: created directory at : artifacts]
[2023-12-21 13:37:43,377: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 13:37:44,289: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-21 13:51:58,909: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2023-12-21 13:51:58,914: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:51:58,914: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:51:58,920: INFO: common: created directory at : artifacts]
[2023-12-21 13:51:58,922: INFO: common: created directory at : artifacts/data_ingestion]
[2023-12-21 13:51:58,922: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-21 13:52:39,388: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-21 13:52:41,536: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2023-12-21 13:52:41,537: INFO: main: >>>>> stage prepare base model started <<<<<]
[2023-12-21 13:52:41,542: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 13:52:41,547: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 13:52:41,548: INFO: common: created directory at : artifacts]
[2023-12-21 13:52:41,550: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 13:52:42,602: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-21 13:52:43,007: INFO: main: >>>>> stage prepare base model completed <<<<<]
[2023-12-21 17:23:51,534: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 17:23:51,549: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 17:23:51,556: INFO: common: created directory at : artifacts]
[2023-12-21 17:24:41,513: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 17:24:41,515: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 17:24:41,520: INFO: common: created directory at : artifacts]
[2023-12-21 17:26:16,399: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 17:26:16,403: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 17:26:16,408: INFO: common: created directory at : artifacts]
[2023-12-21 17:26:16,410: INFO: common: created directory at : artifacts\training]
[2023-12-21 17:34:11,025: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2023-12-21 17:34:11,028: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 17:34:11,033: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 17:34:11,035: INFO: common: created directory at : artifacts]
[2023-12-21 17:34:11,035: INFO: common: created directory at : artifacts/data_ingestion]
[2023-12-21 17:34:11,039: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-21 17:34:27,956: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-12-21 17:34:29,879: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<]
[2023-12-21 17:34:29,879: INFO: main: >>>>> stage prepare base model started <<<<<]
[2023-12-21 17:34:29,884: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 17:34:29,884: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 17:34:29,892: INFO: common: created directory at : artifacts]
[2023-12-21 17:34:29,892: INFO: common: created directory at : artifacts/prepare_base_model]
[2023-12-21 17:34:30,699: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-21 17:34:31,154: INFO: main: >>>>> stage prepare base model completed <<<<<]
[2023-12-21 17:34:31,157: INFO: main: *******************]
[2023-12-21 17:34:31,157: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-12-21 17:34:31,159: INFO: common: yaml file : config\config.yaml loaded successfully]
[2023-12-21 17:34:31,163: INFO: common: yaml file : params.yaml loaded successfully]
[2023-12-21 17:34:31,163: INFO: common: created directory at : artifacts]
[2023-12-21 17:34:31,163: INFO: common: created directory at : artifacts\training]
[2023-12-21 17:35:27,108: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-22 12:17:27,330: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.16.126:8080]
[2023-12-22 12:17:27,330: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 12:17:37,270: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: cross_origin.<locals>.decorator() missing 1 required positional argument: 'f'
[2023-12-22 12:17:37,301: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:17:37] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-22 12:17:37,391: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:17:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-12-22 12:17:56,926: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: cross_origin.<locals>.decorator() missing 1 required positional argument: 'f'
[2023-12-22 12:17:56,935: INFO: _internal: 192.168.16.126 - - [22/Dec/2023 12:17:56] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-22 12:17:57,228: INFO: _internal: 192.168.16.126 - - [22/Dec/2023 12:17:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-12-22 12:18:38,894: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: cross_origin.<locals>.decorator() missing 1 required positional argument: 'f'
[2023-12-22 12:18:38,902: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:18:38] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-22 12:18:39,003: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:18:39] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-12-22 12:19:57,116: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.16.126:8080]
[2023-12-22 12:19:57,116: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 12:20:31,315: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: cross_origin.<locals>.decorator() missing 1 required positional argument: 'f'
[2023-12-22 12:20:31,326: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:20:31] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-22 12:21:52,213: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.16.126:8080]
[2023-12-22 12:21:52,213: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 12:22:01,773: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: cross_origin.<locals>.decorator() missing 1 required positional argument: 'f'
[2023-12-22 12:22:01,781: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:22:01] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-22 12:22:05,229: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: cross_origin.<locals>.decorator() missing 1 required positional argument: 'f'
[2023-12-22 12:22:05,238: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:22:05] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-22 12:22:58,186: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.16.126:8080]
[2023-12-22 12:22:58,186: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 12:23:12,013: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
TypeError: cross_origin.<locals>.decorator() missing 1 required positional argument: 'f'
[2023-12-22 12:23:12,029: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:23:12] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-22 12:27:10,835: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.16.126:8080]
[2023-12-22 12:27:10,835: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-12-22 12:27:31,946: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:27:31] "GET / HTTP/1.1" 200 -]
[2023-12-22 12:28:07,308: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\app.py", line 42, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    test_image = image.load_img(imagename,target_size=(224,224))
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2023-12-22 12:28:07,338: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:28:07] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-12-22 12:28:31,069: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:28:31] "[33mGET /preedict HTTP/1.1[0m" 404 -]
[2023-12-22 12:28:37,918: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:28:37] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2023-12-22 12:29:01,620: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\app.py", line 42, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\Darshan\OneDrive\Desktop\Learning\Kidney-Diseases-Prediction\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    test_image = image.load_img(imagename,target_size=(224,224))
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2023-12-22 12:29:01,638: INFO: _internal: 127.0.0.1 - - [22/Dec/2023 12:29:01] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
